### ISSUE TITLE
build error on debian

### ISSUE THREAD

**Issue by treaki** [diederikdehaas/rtl8812AU#101]
i followed your guide on debian testing, but:

```
$ sudo dkms build -m ${DRV_NAME} -v ${DRV_VERSION}

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make'...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.14.0-3-amd64 (x86_64)
Consult /var/lib/dkms/rtl8812AU/4.3.14/build/make.log for more information.
$ uname -a
Linux ttpdeb03 4.14.0-3-amd64 #1 SMP Debian 4.14.13-1 (2018-01-14) x86_64 GNU/Linux
$ cat /var/lib/dkms/rtl8812AU/4.3.14/build/make.log
DKMS make.log for rtl8812AU-4.3.14 for kernel 4.14.0-3-amd64 (x86_64)
Wed 23 May 15:59:55 CEST 2018
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.14.0-3-amd64/build M=/var/lib/dkms/rtl8812AU/4.3.14/build  modules
make[1]: Entering directory '/usr/src/linux-headers-4.14.0-3-amd64'
  CC [M]  /var/lib/dkms/rtl8812AU/4.3.14/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8812AU/4.3.14/build/include/drv_types.h:32:0,
                 from /var/lib/dkms/rtl8812AU/4.3.14/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8812AU/4.3.14/build/include/osdep_service.h: In function ‘thread_enter’:
/var/lib/dkms/rtl8812AU/4.3.14/build/include/osdep_service.h:343:2: error: implicit declaration of function ‘allow_signal’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
  allow_signal(SIGTERM);
  ^~~~~~~~~~~~
  do_signal
/var/lib/dkms/rtl8812AU/4.3.14/build/include/osdep_service.h: In function ‘flush_signals_thread’:
/var/lib/dkms/rtl8812AU/4.3.14/build/include/osdep_service.h:353:6: error: implicit declaration of function ‘signal_pending’; did you mean ‘timer_pending’? [-Werror=implicit-function-declaration]
  if (signal_pending (current))
      ^~~~~~~~~~~~~~
      timer_pending
/var/lib/dkms/rtl8812AU/4.3.14/build/include/osdep_service.h:355:3: error: implicit declaration of function ‘flush_signals’; did you mean ‘do_signal’? [-Werror=implicit-function-declaration]
   flush_signals(current);
   ^~~~~~~~~~~~~
   do_signal
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.14.0-3-common/scripts/Makefile.build:319: recipe for target '/var/lib/dkms/rtl8812AU/4.3.14/build/core/rtw_cmd.o' failed
make[4]: *** [/var/lib/dkms/rtl8812AU/4.3.14/build/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.14.0-3-common/Makefile:1525: recipe for target '_module_/var/lib/dkms/rtl8812AU/4.3.14/build' failed
make[3]: *** [_module_/var/lib/dkms/rtl8812AU/4.3.14/build] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.14.0-3-amd64'
Makefile:1576: recipe for target 'modules' failed
make: *** [modules] Error 2
$  

```

please help, thanks in advance

**Comment by bilobom** [comment]
add this to include/osdep_service.h

`#include <linux/version.h>`
`#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 11, 0)`
`#include <linux/sched/signal.h>`
`#endif`

**Comment by emiliocb4** [comment]
i've the same issue… also after add the above lines, still the following issue:
cleaning build area...
'make' KVER=4.19.0-0.bpo.5-amd64..........................(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-0.bpo.5-amd64 (x86_64)
Consult /var/lib/dkms/rtl8812AU/4.3.20/build/make.log for more information.
